[Goblin]

; Delay loading Map for Goblins by seconds
load_delay = 15

; Do icons require map fragments to be shown, or be shown always
require_map_fragments = true

; Modify boss icons to display based on require_map_fragments
show_boss_icons = true

; Modify camp icons to display based on require_map_fragments
show_camp_icons = true

; Modify merchant icons to display based on require_map_fragments
; Also requires a MASSEDIT entry for some grace merchants
show_merchant_icons = true

; Change boss icons to red, aka AARON mode
redify_boss_icons = false