#!/usr/bin/env python3
"""Generate GENERATED_DIR/goblin_region_map.{hpp,cpp}: a tile -> game-zone map for
the overlay Progress tab, baked from data/[<profile>/]tile_region_map.json (derived
from BonfireWarpParam graces).

Why: the map-fragment table (goblin_map_tiles.hpp) groups tiles by which fragment
REVEALS them, which merges distinct interior zones into their overworld fragment
(e.g. Roundtable Hold m11_10 -> West Limgrave). For per-region progress we want the
real game zone. tile_region_map's subCategoryId IS a PlaceName id (localizable) that
separates zones properly (Roundtable Hold 11100, Stormveil 10000, Leyndell 11000,
Weeping Peninsula 61002, ...).

The DLL uses this ONLY for interior/underground tiles (areaNo != 60); the overworld
keeps the coarser fragment grouping. Tiles absent here (and profiles with no
tile_region_map.json - only err ships one today) fall back to the fragment grouping,
so this never regresses a profile that lacks the data.

Emitted (sorted by key for binary search):
  RegionTile { uint32_t key; int32_t place_name_id; }   // key = area<<16 | gridX<<8 | gridZ
  RegionName { int32_t place_name_id; const char *en; } // English fallback per zone id
"""
import os, sys, re, json
from pathlib import Path
sys.path.insert(0, os.path.dirname(__file__))
import config

OUT_DIR = config.GENERATED_DIR
SRC = config.DATA_DIR / "tile_region_map.json"
PLACENAME = config.DATA_DIR / "PlaceName_engus.json"

KEY_RE = re.compile(r"^m(\d+)_(\d+)_(\d+)")

# Overworld / underground region names already produced by the fragment grouping
# (goblin_progress REGION_DEFS). An interior tile whose zone name matches one of
# these is left to the fragment grouping instead of baked here - otherwise the
# same-named zone would appear TWICE (e.g. a Caelid cave tagged "Caelid" vs the
# overworld "Caelid"). Keep in sync with REGION_DEFS.
FRAGMENT_NAMES = {
    "Limgrave", "Weeping Peninsula", "Liurnia of the Lakes", "Altus Plateau",
    "Mt. Gelmir", "Caelid", "Greyoll's Dragonbarrow", "Mountaintops of the Giants",
    "Consecrated Snowfield", "Leyndell, Royal Capital", "Ainsel River", "Lake of Rot",
    "Mohgwyn Palace", "Siofra River", "Deeproot Depths", "Crumbling Farum Azula",
    "Miquella's Haligtree", "Gravesite Plain", "Scadu Altus", "Cerulean Coast",
    "Rauh Base", "Abyssal Woods",
}


def _clean(s):
    return re.sub("<[^>]+>", "", s).strip()


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    placenames = {}
    if PLACENAME.exists():
        placenames = json.loads(PLACENAME.read_text(encoding="utf-8"))

    tiles = {}          # key -> place_name_id
    names = {}          # place_name_id -> english name
    name_to_pid = {}    # english name -> canonical place_name_id (dedup interior zones)
    skipped = 0
    if SRC.exists():
        data = json.loads(SRC.read_text(encoding="utf-8"))
        for tile_key, v in data.items():
            m = KEY_RE.match(tile_key)
            if not m:
                continue
            area, gx, gz = int(m.group(1)), int(m.group(2)), int(m.group(3))
            if area > 255 or gx > 255 or gz > 255 or area == 60:
                continue  # overworld keeps the coarse fragment grouping (DLL ignores area 60 here)
            pid = v.get("subCategoryId") or 0
            if pid <= 0:
                continue
            # Prefer the live PlaceName string (what lookup_text will show); this also
            # filters ids with no real PlaceName entry (they'd render unnamed).
            name = _clean(placenames.get(str(pid), "")) or (v.get("subRegion") or "").strip()
            if not name:
                skipped += 1
                continue  # unnamed -> fall back to fragment grouping
            if name in FRAGMENT_NAMES:
                skipped += 1
                continue  # same zone the overworld/fragment grouping already yields -> avoid a duplicate
            # Dedup: two interior ids with the same name collapse to one canonical id.
            pid = name_to_pid.setdefault(name, pid)
            key = (area << 16) | (gx << 8) | gz
            tiles[key] = pid
            names[pid] = name
    else:
        print(f"[region-map] {SRC} not present for this profile; emitting empty map "
              f"(progress falls back to the fragment grouping).")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    hpp = OUT_DIR / "goblin_region_map.hpp"
    cpp = OUT_DIR / "goblin_region_map.cpp"

    hpp.write_text(
        "#pragma once\n#include <cstddef>\n#include <cstdint>\n\n"
        "// AUTO-GENERATED by tools/generate_region_map.py from tile_region_map.json.\n"
        "// Tile -> game-zone (PlaceName id) for the Progress tab. See the generator header.\n"
        "namespace goblin::generated\n{\n"
        "    struct RegionTile { uint32_t key; int32_t place_name_id; }; // key = area<<16|gridX<<8|gridZ\n"
        "    struct RegionName { int32_t place_name_id; const char *en; };\n"
        "    extern const RegionTile REGION_TILES[];\n"
        "    extern const size_t REGION_TILE_COUNT;\n"
        "    extern const RegionName REGION_NAMES[];\n"
        "    extern const size_t REGION_NAME_COUNT;\n"
        "}\n", encoding="utf-8")

    # NOTE: MSVC rejects a zero-size C array (`const T x[] = {};` -> C2466). Profiles
    # without a tile_region_map.json (every non-err profile today) produce empty maps,
    # so emit a single {0,...} sentinel and keep the COUNT accurate (0) - the DLL's
    # binary search is bounded by COUNT and never reads the sentinel.
    out = ['#include "goblin_region_map.hpp"\n', "namespace goblin::generated\n{\n"]
    out.append("const RegionTile REGION_TILES[] = {\n")
    for key in sorted(tiles):
        out.append(f"    {{{key}u, {tiles[key]}}},\n")
    if not tiles:
        out.append("    {0u, 0},  // sentinel: array is empty (COUNT=0); avoids a zero-size array\n")
    out.append("};\n")
    out.append(f"const size_t REGION_TILE_COUNT = {len(tiles)};\n")
    out.append("const RegionName REGION_NAMES[] = {\n")
    for pid in sorted(names):
        out.append(f'    {{{pid}, "{c_escape(names[pid])}"}},\n')
    if not names:
        out.append('    {0, ""},  // sentinel (COUNT=0)\n')
    out.append("};\n")
    out.append(f"const size_t REGION_NAME_COUNT = {len(names)};\n")
    out.append("}\n")
    cpp.write_text("".join(out), encoding="utf-8")
    print(f"[region-map] wrote {len(tiles)} tiles, {len(names)} zones "
          f"(skipped {skipped} unnamed/overworld-dup) -> {cpp}")
    for pid in sorted(names):
        print(f"    zone {pid:8} {names[pid]}")


if __name__ == "__main__":
    main()
